<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Neon Admin Panel" />    
    <title>琴行管理系统</title>
    <link rel="stylesheet" href="/assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css"  id="style-resource-1">
    <link rel="stylesheet" href="/assets/css/font-icons/entypo/css/entypo.css"  id="style-resource-2">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css"  id="style-resource-4">
    <link rel="stylesheet" href="/assets/css/neon-core.min.css"  id="style-resource-5">
    <link rel="stylesheet" href="/assets/css/neon-forms.min.css"  id="style-resource-7">
    <link rel="stylesheet" href="/assets/css/custom.css"  id="style-resource-7">
    <script src="/assets/js/jquery-1.11.0.min.js"></script>
    <script src="/lib/cookie.js" id="script-resource-13"></script>
  </head>

  <body class="page-body login-page login-form-fall">
        <div class="login-container">
          <div class="login-header login-caret">
            <div class="login-content">
              <a href="/" class="logo">
                <img src="/assets/images/logo@2x.png" width="140" alt="" />
              </a>
              <p class="description">琴行管理就要简单快乐</p>
              <div class="login-progressbar-indicator">
                <h3>43%</h3>
                <span>登录中...</span>
              </div>
            </div>
          </div>
          <div class="login-progressbar">
            <div></div>
          </div>
          <div class="login-form">
            <div class="login-content">
              <div class="form-login-error">
                <h3>无法登陆</h3>
                <p>请输入正确的手机号及密码</p>
              </div>
              <form action="/user/login/i/" method="post" role="form" id="form_login">
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="entypo-user"></i>
                    </div>
                    <input type="text" class="form-control" name="username" tabindex="1" id="username" placeholder="手机号" autocomplete="off" />
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="entypo-key"></i>
                    </div>
                    <input type="password" class="form-control" name="password" tabindex="2" id="password" placeholder="密码" autocomplete="off" />
                  </div>
                </div>
                <div class="form-group" id="captchaModal">
                  <div class="input-group" id="captcha-error">
                    <div class="input-group-addon">
                      <i class="entypo-doc-landscape"></i>
                    </div>
                    <input class="form-control login-input" autocomplete="off" type="text" name="captcha" tabindex="3" placeholder="验证码" maxlength="4" id="captcha">
                    <a href="javascript:;" class="captcha pull-right"><img src="/index/captcha/?channel=userLogin" alt="图片验证码" title="更换验证码" width="100" height="40"></a>
                  </div>
                </div>
                <div class="form-group" style="display: none;" id="phoneModal">
                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="entypo-doc-landscape"></i>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <input type="hidden" name="isremember" value="1">
                  <button type="submit" tabindex="4" class="btn btn-primary btn-block btn-login text-align-center">
                    登录
                    <i class="entypo-login"></i>
                  </button>
                </div>                                    
              </form>
            </div>
          </div>
        </div>
        <script type="text/javascript">
        </script>
    <script src="/assets/js/gsap/main-gsap.js" id="script-resource-1"></script>
    <script src="/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js" id="script-resource-2"></script>
    <script src="/assets/js/bootstrap.js" id="script-resource-3"></script>
    <script src="/assets/js/joinable.js" id="script-resource-4"></script>
    <script src="/assets/js/resizeable.js" id="script-resource-5"></script>
    <script src="/assets/js/neon-api.js" id="script-resource-6"></script>
    <script src="/assets/js/cookies.min.js" id="script-resource-7"></script>
    <script src="/assets/js/jquery.validate.min.js" id="script-resource-8"></script>
    <script src="/assets/js/neon-login.js" id="script-resource-9"></script>
    <script src="/assets/js/neon-custom.js" id="script-resource-10"></script>
    <script src="/assets/js/neon-demo.js" id="script-resource-11"></script>
<!--     <script src="/assets/js/neon-skins.js" id="script-resource-12"></script> -->
  </body>
</html>