{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/admin-side.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/admin-info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/admin/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>打卡列表</strong>
      </li>
    </ol>
    <div class="dataTables_wrapper form-inline">
      <div class="row screen-sm">
        <div class="col-lg-1">
          <span>教师ID: <?php echo $teacherId;?></span>
        </div>
        <div class="col-lg-2">
          <span>本月打卡总天数: <?php echo $monthWorkDays;?>天</span>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-striped datatable dataTable text-nowrap custom-table-font-size">
        <thead class="th-color">
          <tr>
            <th>打卡时间</th>
            <th>周末打卡</th>
            <th>迟到打卡</th>
          </tr>
        </thead>
        <tbody>
          <?php if(!empty($pager['data'])):?>
            <?php foreach ($pager['data'] as $key=>$data):?>
            <tr role="row">
              <td><?php echo $data['create_at'];?></td>
              <td><?php echo $data['is_week'] == 0 ? '否' : '是';?></td>
              <td><?php echo $data['is_overdue'] == 0 ? '否' : '是';?></td>
            </tr>
            <?php endforeach;?>
          <?php else:?>
            <td colspan="3" style="text-align: center;">暂无信息</td>
          <?php endif;?>
        </tbody>
      </table>
    </div>
    {include file="../application/index/view/public/pager.phtml" /}
  </div>
</div>
{include file="../application/index/view/public/footer.phtml" /}