<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Neon Admin Panel" />    
    <title>琴行管理系统</title>
    <link rel="stylesheet" href="/assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css"  id="style-resource-1">
    <link rel="stylesheet" href="/assets/css/font-icons/entypo/css/entypo.css"  id="style-resource-2">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css"  id="style-resource-4">
    <link rel="stylesheet" href="/assets/css/neon-core.min.css"  id="style-resource-5">
    <link rel="stylesheet" href="/assets/css/neon-forms.min.css"  id="style-resource-7">
    <link rel="stylesheet" href="/assets/css/custom.css"  id="style-resource-7">
    <script src="/assets/js/jquery-1.11.0.min.js"></script>
    <script src="/lib/cookie.js" id="script-resource-13"></script>
    <script src="/lib/alert.js" id="script-resource-13"></script>
  </head>

  <body class="page-body login-page login-form-fall">
    <div class="login-container">
      <div class="login-header login-caret">
        <div class="login-content">
          <a href="/" class="logo">
            <img src="/assets/images/logo@2x.png" width="140" alt="" />
          </a>
          <p class="description">琴行管理就要简单快乐</p>
          <div class="login-progressbar-indicator">
            <h3>43%</h3>
            <span>注册中...</span>
          </div>
        </div>
      </div>
      <div class="login-progressbar">
        <div></div>
      </div>
      <div class="login-form">
        <div class="login-content">
          <form role="form" id="form_regist">
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="entypo-user"></i>
                </div>
                <input type="text" class="form-control" name="mobile" id="mobile" placeholder="手机号">
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon">
                    <i class="entypo-doc-landscape"></i>
                </div>
                <input type="text" class="form-control login-input" name="code" id="code" placeholder="短信验证码" autocomplete="off" />
                <a href="javascript:;" class="pull-right btn-white" id="getPhone" style="width: 120px;height: 40px;line-height: 40px;text-align: center;color: #000;">获取手机验证码</a>
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="entypo-key"></i>
                </div>
                <input type="password" class="form-control" name="password" id="password" placeholder="密码">
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="entypo-key"></i>
                </div>
                <input type="password" class="form-control" name="sure" id="sure" placeholder="确认密码">
              </div>
            </div>
            <div class="form-group">
              <button class="btn btn-primary btn-block btn-login text-align-center">
                注册
                <i class="entypo-login"></i>
              </button>
            </div>                                  
          </form>
          <div style="text-align: right;color: #999;"><a href="/user/login">前往登录</a></div>
        </div>
      </div>
    </div>
    <div style="position: fixed;top: 0;left: 0;width: 100%;height: 100px;z-index: 10000;" id="alertSuccessWrapper" class="none">
      <div class="alert" style="width:350px;margin: 0 auto;text-align: center;">
        <span id="alertSuccessText"></span>
      </div>
    </div>
    <script type="text/javascript">
      showBtn = getCookie('phone') === '' ? true : false;
      (function(){
        countTime('phone', 'getPhone');
        // 获取手机验证码
        $('#getPhone').click(function() {
          if (showBtn) {
            $.post('/index/captcha/sms', {mobile: $('#mobile').val()}, function(res) {
              pianoAlert(res.status, res.msg, 1500, false);
              if (res.status == true) {
                setCookie('phone', 60, 60 * 1000)
                showBtn = false
                countTime('phone', 'getPhone')
              }
            })
          }
        });
        // 注册
        $('#form_regist').submit(function(e) {
          e.preventDefault();
          const params = $('#form_regist').serializeArray()
          $.post('/user/regist/i', params, function(res) {
            if (res.status == false) {
              pianoAlert(false, res.msg, 1500, false);
            } else {
              pianoAlert(true, res.msg, 1500, false);
              window.location.href = '/user';
            }
          })
        });
      })();
      // 验证码获取倒计时
      function countTime (name, idName) {
        if (getCookie(name) === '') {
          $('#' + idName).text('获取手机验证码');
          showBtn = true;
          return false;
        } else {
          var sec = parseInt(getCookie(name));

          setTimeout(function() {
              sec--;
              $('#' + idName).text(sec);
              setCookie(name, sec, sec * 1000);

              countTime(name, idName);
          }, 1000)
        }
      }
    </script>
    <script src="/assets/js/gsap/main-gsap.js" id="script-resource-1"></script>
    <script src="/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js" id="script-resource-2"></script>
    <script src="/assets/js/bootstrap.js" id="script-resource-3"></script>
    <script src="/assets/js/joinable.js" id="script-resource-4"></script>
    <script src="/assets/js/resizeable.js" id="script-resource-5"></script>
    <script src="/assets/js/neon-api.js" id="script-resource-6"></script>
    <script src="/assets/js/cookies.min.js" id="script-resource-7"></script>
    <script src="/assets/js/jquery.validate.min.js" id="script-resource-8"></script>
    <script src="/assets/js/neon-login.js" id="script-resource-9"></script>
    <script src="/assets/js/neon-custom.js" id="script-resource-10"></script>
    <script src="/assets/js/neon-demo.js" id="script-resource-11"></script>
  </body>
</html>