{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/admin-side.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/admin-info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/admin/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>课程列表</strong>
      </li>
    </ol>
    <div class="dataTables_wrapper form-inline">
      <div class="row screen-sm">
        <div class="col-lg-12">
          <div class="pull-right">
            <a class="btn btn-green btn-sm" id="showAddCourseModal">添加课程</a>
          </div>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-striped datatable dataTable text-nowrap custom-table-font-size">
        <thead class="th-color">
          <tr>
            <th>课程ID</th>
            <th>课程名称</th>
            <th>教室名称</th>
            <th>教师ID</th>
            <th>报名费</th>
            <th>上课人数</th>
            <th>最大上课人数</th>
            <th>开始时间</th>
            <th>结束时间</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <?php if(!empty($pager['data'])):?>
            <?php foreach ($pager['data'] as $key=>$data):?>
              <tr role="row">
                <td><?php echo $data['id'];?></td>
                <td><?php echo $data['course_name'];?></td>
                <td><?php echo $data['rooms'];?></td>
                <td><?php echo $data['teacher_id'];?></td>
                <td><?php echo $data['fee'];?></td>
                <td><?php echo $data['people'];?></td>
                <td><?php echo $data['max_people'];?></td>
                <td><?php echo $data['begin_date'];?></td>
                <td><?php echo $data['end_date'];?></td>
                <td>
                  <a class="btn btn-green btn-sm editCourse" data-id="<?php echo $data['id'];?>">编辑</a>
                  <a class="btn btn-red btn-sm delCourse" data-id="<?php echo $data['id'];?>">删除</a>
                </td>
              </tr>
            <?php endforeach;?>
          <?php else:?>
            <td colspan="9" style="text-align: center;">暂无信息</td>
          <?php endif;?>
        </tbody>
      </table>
    </div>
    {include file="../application/index/view/public/pager.phtml" /}
  </div>

  <!-- 添加弹窗 start -->
  <div class="modal fade" id="addCourseModal">
    <div class="modal-dialog custom-modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4>添加课程信息</h4>
        </div>
        <div class="modal-body">
          <form class="form-horizontal form-groups-bordered form-static" id="addForm">
            <div class="form-group">
              <label class="control-label col-md-3" for="courseName">课程名称</label>
              <div class="col-md-6">
                <input type="text" name="courseName" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="roomsName">教室名称</label>
              <div class="col-md-6">
                <input type="text" name="roomsName" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="teacherId">教师ID</label>
              <div class="col-md-6">
                <input type="text" name="teacherId" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="maxPeople">最大上课人数</label>
              <div class="col-md-6">
                <input type="text" name="maxPeople" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="fee">费用</label>
              <div class="col-md-6">
                <input type="text" name="fee" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="beginDate">开始日期</label>
              <div class="col-md-6">
                <input type="text" class="form-control datepicker" data-format="yyyy-MM-dd" data-callback="rangeChange" name="beginDate">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="endDate">结束日期</label>
              <div class="col-md-6">
                <input type="text" class="form-control datepicker" data-format="yyyy-MM-dd" data-callback="rangeChange" name="endDate">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="begin_at">开始时间</label>
              <div class="col-md-6">
                <input type="text" class="form-control" name="begin_at">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="end_at">结束时间</label>
              <div class="col-md-6">
                <input type="text" class="form-control" name="end_at">
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-info" id="addCourse">添加</button>
        </div>
      </div>
    </div>
  </div>
  <!-- 添加弹窗 end -->

  <!-- 编辑弹窗 start -->
  <div class="modal fade" id="editCourseModal">
    <div class="modal-dialog custom-modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4>编辑课程信息</h4>
        </div>
        <div class="modal-body">
          <form class="form-horizontal form-groups-bordered form-static" id="editForm">
            <input type="text" name="id" hidden="hidden" id="eId">
            <div class="form-group">
              <label class="control-label col-md-3" for="courseName">课程名称</label>
              <div class="col-md-6">
                <input type="text" name="courseName" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="roomsName">教室名称</label>
              <div class="col-md-6">
                <input type="text" name="roomsName" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="teacherId">教师ID</label>
              <div class="col-md-6">
                <input type="text" name="teacherId" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="maxPeople">最大上课人数</label>
              <div class="col-md-6">
                <input type="text" name="maxPeople" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="fee">费用</label>
              <div class="col-md-6">
                <input type="text" name="fee" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="beginDate">开始日期</label>
              <div class="col-md-6">
                <input type="text" class="form-control datepicker" data-format="yyyy-MM-dd" data-callback="rangeChange" name="beginDate">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="endDate">结束日期</label>
              <div class="col-md-6">
                <input type="text" class="form-control datepicker" data-format="yyyy-MM-dd" data-callback="rangeChange" name="endDate">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="begin_at">开始时间</label>
              <div class="col-md-6">
                <input type="text" class="form-control" name="begin_at">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="end_at">结束时间</label>
              <div class="col-md-6">
                <input type="text" class="form-control" name="end_at">
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-info" id="editCourse">编辑</button>
        </div>
      </div>
    </div>
  </div>
  <!-- 编辑弹窗 end -->
</div>

<script type="text/javascript">
  (() => {
    // 添加课程信息
    $('#showAddCourseModal').click(() => {
      $('#addCourseModal').modal('show');
    });
    $('#addCourse').click(() => {
      const params = $('#addForm').serializeArray();
      $.post('/admin/course/add', params, (res) => {
        if (res.status === true) {
          location.reload();
        } else {
          alert(res.msg);
        }
      });
    });
    // 编辑课程信息
    $('.editCourse').click(function() {
      const params = {
        id: $(this).attr('data-id')
      };
      $.post('/admin/course/getcourse', params, (res) => {
        if (res.status === true) {
          $('#eId').val(res.data.id);
          $('#editForm input[name="courseName"]').val(res.data.course_name);
          $('#editForm input[name="roomsName"]').val(res.data.rooms);
          $('#editForm input[name="teacherId"]').val(res.data.teacher_id);
          $('#editForm input[name="maxPeople"]').val(res.data.max_people);
          $('#editForm input[name="fee"]').val(res.data.fee);
          $('#editForm input[name="beginDate"]').val(res.data.begin_date);
          $('#editForm input[name="endDate"]').val(res.data.end_date);
          $('#editForm input[name="begin_at"]').val(res.data.begin_at);
          $('#editForm input[name="end_at"]').val(res.data.end_at);
          $('#editCourseModal').modal('show');
        }
      });
    });
    $('#editCourse').click(() => {
      const params = $('#editForm').serializeArray();
      $.post('/admin/course/update', params, (res) => {
        if (res.status === true) {
          location.reload();
        } else {
          alert(res.msg);
        }
      });
    });
    // 删除课程信息
    $('.delCourse').click(function() {
      if (window.confirm('确定删除该课程？')) {
        const params = {
          id: $(this).attr('data-id')
        }
        $.post('/admin/course/del', params, (res) => {
          if (res.status === true) {
            location.reload();
          } else {
            alert(res.msg);
          }
        });
      }
    });
  })();
</script>
{include file="../application/index/view/public/footer.phtml" /}