{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/teacher-side.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/teacher-info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/teacher/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>学生信息</strong>
      </li>
    </ol>
    <div class="table-responsive">
      <table class="table table-bordered table-striped datatable dataTable text-nowrap custom-table-font-size">
        <thead class="th-color">
          <tr>
            <th>学号</th>
            <th>姓名</th>
            <th>手机号</th>
          </tr>
        </thead>
        <tbody id="content">
        </tbody>
      </table>
    </div>
  </div>
</div>

<script type="text/javascript">
  (() => {
    const url = window.location.href;
    let idx = url.indexOf('?id=');
    const id = url.substring(idx + 4);
    const params = {
      id: id
    }
    $.post('/teacher/index/courseStudents', params, function(res) {
      if (res.status === true) {
        for (let i in res.data) {
          let str = '<tr role="row">';
          str += `<td>${res.data[i].user_no}</td>`;
          str += `<td>${res.data[i].user_name}</td>`;
          str += `<td>${res.data[i].mobile}</td></tr>`;
          $('#content').append(str);
        }
      }
    })
  })();
</script>
{include file="../application/index/view/public/footer.phtml" /}