{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/admin-side.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/admin-info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/admin/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>数据统计</strong>
      </li>
    </ol>

    <h2>数据预览</h2>
    <div class="row">
      <div class="col-sm-4">
        <div class="tile-stats tile-aqua">
          <div class="num"><span><?php echo $goodsTotal ;?>件</span></div>
          <h3>商品总库存</h3>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="tile-stats tile-aqua">
          <div class="num"><span><?php echo $totalMoney ;?>元</span></div>
          <h3>总出售金额</h3>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="tile-stats tile-aqua">
          <div class="num"><span><?php echo $totalNum ;?>件</span></div>
          <h3>出售商品数量</h3>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <div class="tab-pane active">
        <div id="containerBuy" class="chart"></div>
      </div>
    </div>
    <div class="panel-body">
      <div class="tab-pane active">
        <div id="containerCourse" class="chart"></div>
      </div>
    </div>
  </div>
</div>

{load  file="/lib/highcharts/highcharts.js" /}
{load  file="/lib/highcharts/modules/data.js" /}

<script>
(() => {
  let chartBuy = Highcharts.chart('containerBuy', {
    chart: {
      type: 'bar'
    },
    title: {
      text: '前三销售商品'
    },
    xAxis: {
      categories: ['销售数量'],
      title: {
        text: null
      }
    },
    series: [{
      name: '<?php echo $goodsTop3[0]['goods']['goods_name'];?>',
      data: [<?php echo $goodsTop3[0]['allBuy'];?>]
    }, {
      name: '<?php echo $goodsTop3[1]['goods']['goods_name'];?>',
      data: [<?php echo $goodsTop3[1]['allBuy'];?>]
    }, {
      name: '<?php echo $goodsTop3[2]['goods']['goods_name'];?>',
      data: [<?php echo $goodsTop3[2]['allBuy'];?>]
    }]
  });
  let chartCourse = Highcharts.chart('containerCourse', {
    chart: {
      type: 'bar'
    },
    title: {
      text: '前五课程'
    },
    xAxis: {
      categories: ['课程数量'],
      title: {
        text: null
      }
    },
    series: [{
      name: '<?php echo $courseTop5[0]['course_name'];?>',
      data: [<?php echo $courseTop5[0]['people'];?>]
    }, {
      name: '<?php echo $courseTop5[1]['course_name'];?>',
      data: [<?php echo $courseTop5[1]['people'];?>]
    }, {
      name: '<?php echo $courseTop5[2]['course_name'];?>',
      data: [<?php echo $courseTop5[2]['people'];?>]
    }, {
      name: '<?php echo $courseTop5[3]['course_name'];?>',
      data: [<?php echo $courseTop5[3]['people'];?>]
    }, {
      name: '<?php echo $courseTop5[4]['course_name'];?>',
      data: [<?php echo $courseTop5[4]['people'];?>]
    }]
  });
})();
</script>
{include file="../application/index/view/public/footer.phtml" /}