{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/admin-side.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/admin-info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/admin/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>数据统计</strong>
      </li>
    </ol>
  </div>
</div>
<?php var_dump($goodsTotal);?>
<?php var_dump($totalMoney);?>
<?php var_dump($totalNum);?>
<?php var_dump($goodsTop3);?>
<?php var_dump($courseTop5);?>
{include file="../application/index/view/public/footer.phtml" /}