{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/admin-side.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/admin-info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/admin/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>教师工资条</strong>
      </li>
    </ol>
    <div class="dataTables_wrapper form-inline">
      <div class="table-responsive">
        <table class="table table-bordered table-striped datatable dataTable text-nowrap custom-table-font-size">
          <thead class="th-color">
            <tr>
              <th>教师姓名</th>
              <th>正常打卡</th>
              <th>加班天数</th>
              <th>迟到天数</th>
              <th>迟到加班天数</th>
              <th>正常工资</th>
              <th>加班补贴</th>
              <th>迟到扣款</th>
              <th>总工资</th>
            </tr>
          </thead>
          <tbody>
            <?php if(!empty($pager['data'])):?>
              <?php foreach ($pager['data'] as $key=>$data):?>
                <tr role="row">
                  <td><?php echo $data['teacher_name'];?></td>
                  <td><?php echo $data['workDays'];?></td>
                  <td><?php echo $data['isWeekDays'];?></td>
                  <td><?php echo $data['overdueDays'];?></td>
                  <td><?php echo $data['overdueOfIsWeekDays'];?></td>
                  <td><?php echo $data['commonSalary'];?></td>
                  <td><?php echo $data['addSalary'];?></td>
                  <td><?php echo $data['overdueSalary'];?></td>
                  <td><?php echo $data['monthSalary'];?></td>
                </tr>
              <?php endforeach;?>
            <?php else:?>
              <td colspan="9" style="text-align: center;">暂无信息</td>
            <?php endif;?>
          </tbody>
        </table>
      </div>
      {include file="../application/index/view/public/pager.phtml" /}
    </div>
  </div>
</div>
{include file="../application/index/view/public/footer.phtml" /}