{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/admin-side.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/admin-info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/admin/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>教师工资条</strong>
      </li>
    </ol>
    <div class="dataTables_wrapper form-inline">
      <div class="row screen-sm">
        <div class="col-lg-12">
          <div class="pull-right">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{include file="../application/index/view/public/footer.phtml" /}