{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/admin-side.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/admin-info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/admin/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>商品列表</strong>
      </li>
    </ol>
    <div class="dataTables_wrapper form-inline">
      <div class="row screen-sm">
        <div class="col-lg-12">
          <div class="pull-right">
            <a class="btn btn-green btn-sm" id="showAddGoodsModal">添加商品</a>
          </div>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-striped datatable dataTable text-nowrap custom-table-font-size">
        <thead class="th-color">
          <tr>
            <th>商品名称</th>
            <th>价格</th>
            <th>上架情况</th>
            <th>库存量</th>
            <th>描述</th>
            <th>图片</th>
            <td>操作</td>
          </tr>
        </thead>
        <tbody>
          <?php if(!empty($pager['data'])):?>
            <?php foreach ($pager['data'] as $key=>$data):?>
              <tr role="row">
                <td><?php echo $data['goods_name'];?></td>
                <td><?php echo $data['price'];?></td>
                <td><?php echo ($data['is_down'] == 0 ? '上架' : '下架');?></td>
                <td><?php echo $data['stock'];?></td>
                <td><?php echo $data['describe'];?></td>
                <td><img src="<?php echo $data['photo']?$data['photo']:'';?>" width="60"></td>
                <td>
                  <a class="btn btn-green btn-sm showStockModal" data-id="<?php echo $data['id'];?>">添加库存</a>
                  <a class="btn btn-green btn-sm editInfo" data-id="<?php echo $data['id'];?>">修改信息</a>
                  <?php if ($data['is_down'] == 0) : ;?>
                    <a class="btn btn-red btn-sm goodsDown" data-id="<?php echo $data['id'];?>">下架</a>
                  <?php endif ;?>
                </td>
              </tr>
            <?php endforeach;?>
          <?php else:?>
            <td colspan="9" style="text-align: center;">暂无信息</td>
          <?php endif;?>
        </tbody>
      </table>
    </div>
    {include file="../application/index/view/public/pager.phtml" /}
  </div>

  <!-- 添加弹窗 start -->
  <div class="modal fade" id="addGoodsModal">
    <div class="modal-dialog custom-modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"  aria-hidden="true">&times;</button>
          <h4>添加商品信息</h4>
        </div>
        <div class="modal-body">
          <form class="form-horizontal form-groups-bordered form-static"  enctype="multipart/form-data"  id="addForm">
            <div class="form-group">
              <label class="control-label col-md-3" for="name">商品名称</label>
              <div class="col-md-6">
                <input type="text" name="name" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="price">价格</label>
              <div class="col-md-6">
                <input type="text" name="price" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label for="isDown" class="col-sm-3 control-label">是否上架</label>
              <div class="col-sm-9">
                  <label class="radio-inline">
                    <input type="radio" name="isDown" value="0" checked>上架
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="isDown" value="1">下架
                  </label>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="stock">库存量</label>
              <div class="col-md-6">
                <input type="text" name="stock" class="form-control">
              </div>
            </div>
              <div class="form-group">
                  <label class="control-label col-md-3" for="goods_photo">图片</label>
                  <div class="col-md-6">
                      <input type="file" name="" id="addgoodsphoto">
                  </div>
              </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="describe">描述</label>
              <div class="col-md-6">
                <textarea class="form-control" name="describe"></textarea>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-info" id="addGoods">添加</button>
        </div>
      </div>
    </div>
  </div>
  <!-- 添加弹窗 end -->

  <!-- 修改弹窗 start -->
  <div class="modal fade" id="editGoodsModal">
    <div class="modal-dialog custom-modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" enctype="multipart/form-data"  aria-hidden="true">&times;</button>
          <h4>修改商品信息</h4>
        </div>
        <div class="modal-body">
          <form class="form-horizontal form-groups-bordered form-static" id="editForm">
            <input type="text" name="id" hidden="hidden" id="eId">
            <div class="form-group">
              <label class="control-label col-md-3" for="goods_name">商品名称</label>
              <div class="col-md-6">
                <input type="text" name="name" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="price">价格</label>
              <div class="col-md-6">
                <input type="text" name="price" class="form-control">
              </div>
            </div>
              <div class="form-group">
                  <label class="control-label col-md-3" for="goods_photo">图片</label>
                  <div class="col-md-6">
                      <input type="file" name="" id="editgoodsphoto">
                  </div>
              </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="describe">描述</label>
              <div class="col-md-6">
                <textarea class="form-control" name="describe"></textarea>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-info" id="editGoods">修改</button>
        </div>
      </div>
    </div>
  </div>
  <!-- 修改弹窗 end -->

  <!-- 添加库存 start -->
  <div class="modal fade" id="addStockModal">
    <div class="modal-dialog custom-modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4>添加商品库存</h4>
        </div>
        <div class="modal-body">
          <form class="form-horizontal form-groups-bordered form-static" id="addStockForm">
            <input type="number" name="id" id="stockId" hidden="hidden">
            <div class="form-group">
              <label class="control-label col-md-3" for="num">添加数量</label>
              <div class="col-md-6">
                <input type="number" name="num" class="form-control" id="stockNum">
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-info" id="addStock">添加</button>
        </div>
      </div>
    </div>
  </div>
  <!-- 添加库存 end -->
</div>
<script type="text/javascript">
  (() => {
    // 添加商品
    $('#showAddGoodsModal').click(() => {
      $('#addGoodsModal').modal('show');
    });
    $('#addGoods').click(() => {
      const params = $('#addForm').serializeArray();
      let formData = new FormData();
      formData.append("goods_photo", $("#addgoodsphoto")[0].files[0]);
      for (let i in params) {
          formData.append(params[i].name, params[i].value)
      }
        $.ajax({
            url: "/admin/goods/add",
            type: "post",
            data: formData,
            async: true,
            cache: false,
            contentType: false,
            processData: false,
            success: function(res){
                if (res.status === true) {
                    location.reload();
                } else {
                    alert(res.msg);
                }
            },
            error: function(err){
                alert('网络错误');
            }
        })
    });
    // 获取商品详情
    $('.editInfo').click(function() {
      const params = {
        id: $(this).attr('data-id')
      }
      $.post('/admin/goods/getgoods', params, (res) => {
        $('#eId').val(res.data.id);
        $('#editForm input[name="name"]').val(res.data.goods_name);
        $('#editForm input[name="price"]').val(res.data.price);
        $('#editForm textarea[name="describe"]').val(res.data.describe);
        $('#editGoodsModal').modal('show');
      });
    });
    // 修改商品信息
    $('#editGoods').click(()=> {
      const params = $('#editForm').serializeArray();
      let formData = new FormData();
      console.log($("#editgoodsphoto")[0].files[0]);
      formData.append("goods_photo", $("#editgoodsphoto")[0].files[0]);
      for (let i in params) {
          formData.append(params[i].name, params[i].value)
      }
        $.ajax({
            url: "/admin/goods/update",
            type: "post",
            data: formData,
            async: true,
            cache: false,
            contentType: false,
            processData: false,
            success: function(res){
                if (res.status === true) {
                    location.reload();
                } else {
                    alert(res.msg);
                }
            },
            error: function(err){
                alert('网络错误');
            }
        })
    });
    // 添加库存
    $('.showStockModal').click(function() {
      $('#stockId').val($(this).attr('data-id'));
      $('#addStockModal').modal('show');
    });
    $('#addStock').click(() => {
      const params = $('#addStockForm').serializeArray();
      $.post('/admin/goods/addstock', params, (res) => {
        if (res.status === true) {
          location.reload();
        } else {
          alert(res.msg);
        }
      });
    });
    // 下架商品
    $('.goodsDown').click(function() {
      if (confirm('确定下架该商品？')) {
        const params = {
          id: $(this).attr('data-id')
        }
        $.post('/admin/goods/down', params, (res) => {
          if (res.status === true) {
            location.reload();
          } else {
            alert(res.msg);
          }
        })
      }
    });
  })();
</script>
{include file="../application/index/view/public/footer.phtml" /}