<div class="sidebar-menu sidebar-width">
  <header class="logo-env">
    <div class="logo custom-logo-left">
      <a href="/" style="line-height: 32px;display: inline-block;text-align: center;width: 160px;font-size: 16px;color: #fff;">琴行-管理员端</a>
    </div>
    <div class="sidebar-collapse custom-collapse-top">
      <a href="index.html#" class="sidebar-collapse-icon with-animation"><i class="entypo-menu"></i></a>
    </div>
    <div class="sidebar-mobile-menu visible-xs">
      <a href="index.html#" class="with-animation"><i class="entypo-menu"></i></a>
    </div>
  </header>
  <ul id="main-menu" class="">
      <li>
        <a href="/admin/index">
          <i class="entypo-user"></i>
          <span>管理员管理</span>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="entypo-user"></i>
          <span>教师管理</span>
        </a>
        <ul>
          <li>
            <a href="/admin/teacher/index">
              <span>教师列表</span>
            </a>
          </li>
          <!-- <li>
            <a href="/admin/teacher/workdetail">
              <span>打卡列表</span>
            </a>
          </li> -->
        </ul>
      </li>
      <li>
        <a href="/admin/user/index">
          <i class="entypo-user"></i>
          <span>学生管理</span>
        </a>
      </li>
      <li>
        <a href="/admin/course/index">
          <i class="entypo-menu"></i>
          <span>课程管理</span>
        </a>
      </li>
    </ul>
</div>