    <script src="/assets/js/gsap/main-gsap.js" id="script-resource-1"></script>
    <script src="/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js" id="script-resource-2"></script>
    <script src="/assets/js/bootstrap.js" id="script-resource-3"></script>
    <script src="/assets/js/joinable.js" id="script-resource-4"></script>
    <script src="/assets/js/resizeable.js" id="script-resource-5"></script>
    <script src="/assets/js/neon-api.js" id="script-resource-6"></script>
    <script src="/assets/js/neon-custom.js" id="script-resource-10"></script>
    <script src="/plugins/datetimepicker/bootstrap-datetimepicker.min.js"></script>
    <script src="/assets/js/daterangepicker/daterangepicker.js"></script>
    <script src="/assets/js/bootstrap-datepicker.js"></script>
    <script src="/assets/js/bootstrap-colorpicker.min.js"></script>
    <script src="/assets/js/bootstrap-timepicker.min.js"></script>
    <script src="/assets/js/daterangepicker/moment.min.js"></script>
    <script src="/assets/js/daterangepicker/daterangepicker.js"></script>
  </body>
</html>