<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Neon Admin Panel" />
    <title>琴行管理系统</title>
    <link rel="stylesheet" href="/assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css"  id="style-resource-1">
    <link rel="stylesheet" href="/assets/css/font-icons/entypo/css/entypo.css"  id="style-resource-2">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css"  id="style-resource-4">
    <link rel="stylesheet" href="/assets/css/neon-core.min.css"  id="style-resource-5">
    <link rel="stylesheet" href="/assets/css/neon-forms.min.css"  id="style-resource-7">
    <link rel="stylesheet" href="/assets/css/bootstrapValidator.css"  id="style-resource-8">
    <link rel="stylesheet" href="/assets/css/font-icons/font-awesome/css/font-awesome.min.css"  id="style-resource-9">
    <link rel="stylesheet" type="text/css" href="/plugins/datetimepicker/bootstrap-datetimepicker.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/js/daterangepicker/daterangepicker-bs3.css" />
    <link rel="stylesheet" type="text/css" href="/lib/codemirror/lib/codemirror.css" />
    <link rel="stylesheet" type="text/css" href="/lib/codemirror/addon/fold/foldgutter.css" />
    <link rel="stylesheet" type="text/css" href="/lib/codemirror/theme/dracula.css" />
    <script src="/assets/js/jquery-1.11.0.min.js"></script>
    <script src="/assets/js/bootstrapValidator.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/ueditor/ueditor.all.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/lib/codemirror.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/addon/edit/matchbrackets.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/addon/fold/foldcode.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/addon/fold/foldgutter.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/addon/fold/brace-fold.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/addon/fold/comment-fold.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/mode/htmlmixed/htmlmixed.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/mode/xml/xml.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/mode/javascript/javascript.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/mode/css/css.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/mode/clike/clike.js"></script>
    <script type="text/javascript" charset="utf-8" src="/lib/codemirror/mode/php/php.js"></script>
  </head>

  <body class="page-body" data-url="/">
