<style type="text/css">
.pager{
  height: 40px;
  width: 960px;
  margin:10px auto;
}
.pager-list{
  width: 718px;
  margin-right: 100px;
  padding-top: 3px;
  float: right;
  text-align: center;
  height: 40px;
}
.pager-total{
  width: 100px;
  padding-left: 40px;
  color: #271f18;
  font-size: 12px;
  float: left;
  line-height: 40px;
}
.pager-total span {
  color: grey;
  font-size: 14px;
}
.pager-list span ,.pager-list a:link,.pager a:visited{
  display: inline-block;
  border: 1px solid rgba(219, 209, 232, 0.46);
  text-decoration: none;
  padding: 5px 10px;
}

.pager-list a:hover,.pager-list a:active{
  background-color: rgb(173, 195, 232);
}
</style>
<div class="pager">
  <div class="pager-total">总数：<span ><?php echo $pager['total'];?></span></div>
  <div class="pager-list">
    <?php if($pager['last_page']!=1):?>
        <?php if($pager['current_page']!=1):?>
          <a href="<?php echo uri(['page'=>1]);?>">首页</a>
          <a href="<?php echo uri(['page'=>$pager['current_page']-1]);?>">上一页</a>
        <?php endif;?>
        <?php if($pager['current_page']-2>=1):?>
          <a href="<?php echo uri(['page'=>$pager['current_page']-2]);?>"><?php echo $pager['current_page']-2;?></a>
          <a href="<?php echo uri(['page'=>$pager['current_page']-1]);?>"><?php echo $pager['current_page']-1;?></a>
        <?php elseif($pager['current_page'] == 2):?>
          <a href="<?php echo uri(['page'=>$pager['current_page']-1]);?>"><?php echo $pager['current_page']-1;?></a>
        <?php endif;?>
        <span><?php echo $pager['current_page'];?></span>
        <?php $end = $pager['last_page']-2>$pager['current_page']?$pager['current_page']+2:$pager['last_page'];?>
        <?php for ($i=$pager['current_page']+1;$i<=$end;$i++):?>
          <a href="<?php echo uri(['page'=>$i]);?>"><?php echo $i;?></a>
        <?php endfor;?>
        <?php if($pager['current_page']!=$pager['last_page']):?>
          <a href="<?php echo uri(['page'=>$pager['current_page']+1]);?>">下一页</a>
          <a href="<?php echo uri(['page'=>$pager['last_page']]);?>">尾页</a>
        <?php endif;?>
    <?php endif;?>
  </div>
</div>