<div class="sidebar-menu sidebar-width">
  <header class="logo-env">
    <div class="logo custom-logo-left">
      <a href="/" style="line-height: 32px;display: inline-block;text-align: center;width: 160px;font-size: 16px;color: #fff;">琴行-教师端</a>
    </div>
    <div class="sidebar-collapse custom-collapse-top">
      <a href="index.html#" class="sidebar-collapse-icon with-animation"><i class="entypo-menu"></i></a>
    </div>
    <div class="sidebar-mobile-menu visible-xs">
      <a href="index.html#" class="with-animation"><i class="entypo-menu"></i></a>
    </div>
  </header>
  <ul id="main-menu" class="">
      <li>
        <a href="/teacher/index">
          <i class="entypo-user"></i>
          <span>个人信息</span>
        </a>
      </li>
      <li>
        <a href="/teacher/index/courses">
          <i class="entypo-menu"></i>
          <span>课程列表</span>
        </a>
      </li>
    </ul>
</div>