<div class="row">
  <div class="col-md-6 col-sm-8 clearfix">
    <ul class="user-info pull-left pull-none-xsm">
      <li class="profile-info dropdown">
        <a href="index.html#" class="dropdown-toggle" data-toggle="dropdown">
          <img src="/assets/images/avatar.jpg" alt="" class="img-circle" width="44">
        </a>
      </li>
    </ul>
  </div>
  <div class="col-md-6 col-sm-4 clearfix hidden-xs">
    <ul class="list-inline links-list pull-right">
      <li>
        <a href="/teacher/logout/">
          用户退出 <i class="entypo-logout right"></i>
        </a>
      </li>
    </ul>
  </div>
</div>
<hr>
