<div class="sidebar-menu sidebar-width">
  <header class="logo-env">
    <div class="logo custom-logo-left">
      <a href="/" style="line-height: 32px;display: inline-block;text-align: center;width: 160px;font-size: 16px;color: #fff;">琴行-用户端</a>
    </div>
    <div class="sidebar-collapse custom-collapse-top">
      <a href="index.html#" class="sidebar-collapse-icon with-animation"><i class="entypo-menu"></i></a>
    </div>
    <div class="sidebar-mobile-menu visible-xs">
      <a href="index.html#" class="with-animation"><i class="entypo-menu"></i></a>
    </div>
  </header>
  <ul id="main-menu" class="">
      <!-- add class "multiple-expanded" to allow multiple submenus to open -->
      <!-- class "auto-inherit-active-class" will automatically add "active" class for parent elements who are marked already with class "active" -->
      <!-- Search Bar -->
      
      <li>
        <a href="/user/index">
          <i class="entypo-user"></i>
          <span>个人信息</span>
        </a>
      </li>
      <li>
        <a href="/user/goods/index">
          <i class="entypo-menu"></i>
          <span>商品列表</span>
        </a>
      </li>
      <li>
        <a href="/user/index/myorders">
          <i class="entypo-menu"></i>
          <span>个人订单列表</span>
        </a>
      </li>
    </ul>
</div>