{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/user-side.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/user-info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/user/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>课程列表</strong>
      </li>
    </ol>
    <div class="dataTables_wrapper form-inline">
      <div class="row screen-sm">
        <div class="col-lg-12">
          <div class="pull-right">
            <a class="btn btn-green btn-sm" href="/user/index/mycourse">已报名课程</a>
          </div>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-striped datatable dataTable text-nowrap custom-table-font-size">
        <thead class="th-color">
          <tr>
            <th>课程名称</th>
            <th>教室名称</th>
            <th>教师ID</th>
            <th>报名费</th>
            <th>上课人数</th>
            <th>最大上课人数</th>
            <th>开始时间</th>
            <th>结束时间</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <?php if(!empty($pager['data'])):?>
            <?php foreach ($pager['data'] as $key=>$data):?>
              <tr role="row">
                <td><?php echo $data['course_name'];?></td>
                <td><?php echo $data['rooms'];?></td>
                <td><?php echo $data['teacher_id'];?></td>
                <td><?php echo $data['fee'];?></td>
                <td><?php echo $data['people'];?></td>
                <td><?php echo $data['max_people'];?></td>
                <td><?php echo $data['begin_date'];?></td>
                <td><?php echo $data['end_date'];?></td>
                <td>
                  <?php if (time() < strtotime($data['begin_date'])) : ;?>
                    <a class="btn btn-green btn-sm applyCourse" data-id="<?php echo $data['id'];?>">报名</a>
                  <?php else:?>
                    <span style="color: #999;font-size: 12px;">已过报名时间</span>
                  <?php endif;?>
                </td>
              </tr>
            <?php endforeach;?>
          <?php else:?>
            <td colspan="9" style="text-align: center;">暂无信息</td>
          <?php endif;?>
        </tbody>
      </table>
    </div>
    {include file="../application/index/view/public/pager.phtml" /}
  </div>


</div>

<<script>
  (() => {
    // 课程报名
    $('.applyCourse').click(function() {
      if (window.confirm('确定报名该课程？')) {
        const params = {
          courseId: $(this).attr('data-id')
        }
        $.post('/user/index/attend', params, (res) => {
          if (res.status === true) {
            location.reload();
          } else {
            alert(res.msg);
          }
        });
      }
    });
  })();
</script>
{include file="../application/index/view/public/footer.phtml" /}