{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/user-side.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/user-info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/user/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>订单列表</strong>
      </li>
    </ol>
    <div class="table-responsive">
      <table class="table table-bordered table-striped datatable dataTable text-nowrap custom-table-font-size">
        <thead class="th-color">
          <tr>
            <th>商品Id</th>
            <th>购买数量</th>
            <th>购买折扣</th>
            <th>金额</th>
            <th>订单状态</th>
            <th>收获地址</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <?php if(!empty($pager['data'])):?>
            <?php foreach ($pager['data'] as $key=>$data):?>
              <tr role="row">
                <td><?php echo $data['goods_id'];?></td>
                <td><?php echo $data['buy_num'];?></td>
                <td><?php echo $data['discount'];?></td>
                <td><?php echo $data['amount'];?></td>
                <td><?php echo $orderStatus[$data['status']];?></td>
                <td><?php echo $data['address'];?></td>
                <td>
                  <a class="btn btn-red btn-sm cancel" data-id="<?php echo $data['id'] ;?>">取消订单</a>
                </td>
              </tr>
            <?php endforeach;?>
          <?php else:?>
            <td colspan="7" style="text-align: center;">暂无信息</td>
          <?php endif;?>
        </tbody>
      </table>
    </div>
    {include file="../application/index/view/public/pager.phtml" /}
  </div>
</div>
<script type="text/javascript">
  (() => {
    $('.cancel').click(function() {
      if (window.confirm('确定取消该订单？')) {
        const params = {
          orderId: $(this).attr('data-id')
        }
        $.post('/user/index/cancelOrder', params, (res) => {
          if (res.status === true) {
            location.reload();
          } else {
            alert(res.msg);
          }
        });
      }
    })
  })();
</script>
{include file="../application/index/view/public/footer.phtml" /}